version: "3.9"
services:
  api:
    image: arvintian/cae-api:1.1.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "api_data:/channel"
    ports:
      - "0.0.0.0:2222:2222"
    environment:
      - PORT=5000
      - WORKERS=2
      - REDIS_URL=redis://redis:6379/0
      - REDIS_KEY_PREFIX=cae
      - DOCKER_NETWORK=caenet
      - DOCKER_NETWORK_BLOCKS=172.28.2.0/24,172.28.3.0/24
      - SSHD_PORT=2222
    labels:
      cae.infra: "api"
      traefik.http.routers.cae-api.entrypoints: "http80"
      traefik.http.routers.cae-api.middlewares: "cae-infra-auth"
      traefik.http.routers.cae-api.rule: "Host(`cae.yourdomain.com`)&&PathPrefix(`/api`)"
      traefik.http.routers.cae-api.service: "cae-api-service"
      traefik.http.services.cae-api-service.loadbalancer.server.port: 5000
    networks:
      caenet:
        ipv4_address: 172.28.1.4
    depends_on:
      - redis
    links:
      - redis
  ui:
    image: arvintian/cae-ui:1.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    labels:
      cae.infra: "ui"
      traefik.http.routers.cae-ui.entrypoints: "http80"
      traefik.http.routers.cae-ui.middlewares: "cae-infra-auth"
      traefik.http.routers.cae-ui.rule: "Host(`cae.yourdomain.com`)&&PathPrefix(`/`)"
      traefik.http.routers.cae-ui.service: "cae-ui-service"
      traefik.http.services.cae-ui-service.loadbalancer.server.port: 80
    networks:
      caenet:
        ipv4_address: 172.28.1.3
    depends_on:
      - api
  traefik:
    image: traefik:v2.4.8
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --api=true
      - --api.dashboard=true
      - --entrypoints.http80=true
      - --entrypoints.http80.address=:80
      - --log=true
      - --log.level=info
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.constraints=LabelRegex(`cae.infra`,`.+`)
      - --providers.redis=true
      - --providers.redis.endpoints=redis:6379
      - --providers.redis.rootkey=cae/ingress
    ports:
      - "0.0.0.0:80:80"
    labels:
      cae.infra: "traefik"
      traefik.http.middlewares.cae-infra-auth.basicauth.users: "traefik:$$apr1$$K25PBQJT$$ukKUrPk9K0gsRjS83Xv5J0"
      traefik.http.routers.traefik-api.entrypoints: "http80"
      traefik.http.routers.traefik-api.middlewares: "cae-infra-auth"
      traefik.http.routers.traefik-api.rule: "Host(`traefik.yourdomain.com`)&&PathPrefix(`/api`)"
      traefik.http.routers.traefik-api.service: "api@internal"
      traefik.http.routers.traefik-dashboard.entrypoints: "http80"
      traefik.http.routers.traefik-dashboard.middlewares: "cae-infra-auth"
      traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.yourdomain.com`)&&PathPrefix(`/`)"
      traefik.http.routers.traefik-dashboard.service: "dashboard@internal"
    networks:
      caenet:
        ipv4_address: 172.28.1.2
    depends_on:
      - api
      - ui
    links:
      - redis
  redis:
    image: redis:5.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
    networks:
      caenet:
        ipv4_address: 172.28.1.1
    volumes:
      - "redis_data:/data"
volumes:
  api_data:
    name: cae_api_data
    driver: local
    labels:
      cae.infra: "volume"
  redis_data:
    name: cae_redis_data
    driver: local
    labels:
      cae.infra: "volume"
networks:
  caenet:
    name: caenet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"
    labels:
      cae.infra: "network"
